### PR TITLE
Rename secret spec file and clarify how to get the app endpoint

### PR DESCRIPTION
**Pull request by renier**
Deployed this on OpenShift following the instructions and found
a couple of hicups.

### CODE REVIEW

**Comment by cooktheryan** [comment]
@husky-parul

**Review by husky-parul — COMMENTED** [review]
Can use `oc get routes` to get the endpoints.  

Maybe add another section (e.g Check application status) to see the full status of the deployment for `oc status`?

**Comment by renier** [comment]
@husky-parul Ok, I just changed the command to `oc get routes` to let folks know how to go and check their work on the web browser.

**Comment by husky-parul** [comment]
Fixes:
1. Spellcheck 
2. README edits

**Pull request merged**
